version: "3.9"
services:
  mysql:
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    # platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3307
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081
  mailpit:
    image: axllent/mailpit
    container_name: mailpit-portfolio
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 8026:8026
      - 1026:1026
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1