version: "3.9"
services:
  mysql:
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    # platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  mailpit:
    image: axllent/mailpit
    container_name: mailpit-portfolio
    restart: always
    volumes:
      - ./data:/data
    # ports:
    #   - 8026:8026
    #   - 1026:1026
    ports:
      - 9090:8025  # Map host 9090 → Mailpit's UI port 8025
      - 9091:1025  # Map host 9091 → Mailpit's SMTP port 1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1