<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\View;
use App\View\Composers\TestimonialsComposer;

use League\CommonMark\CommonMarkConverter;
use League\CommonMark\Environment\Environment;
use App\Helpers\LazyLoadImageRenderer;
use League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension;
use League\CommonMark\Extension\CommonMark\Node\Inline\Image;
use League\CommonMark\GithubFlavoredMarkdownConverter;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        // Add testimonials to components that render them.
        View::composer([
            'components.newsletter-opt-in',
            'resources.clarity-call',
        ], TestimonialsComposer::class);

        // Add lazy loading to images generated by Markdown content.
        // $this->app->singleton(GithubFlavoredMarkdownConverter::class, function ($app) {
        //     $environment = new Environment();
        //     $environment->addExtension(new CommonMarkCoreExtension());
        //     $environment->addRenderer(Image::class, new LazyLoadImageRenderer());

        //     return new GithubFlavoredMarkdownConverter( $environment );
        // });
    }
}
